name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: taiki-e/install-action@cargo-hack
    - name: Check
      run: cargo check --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose
    - name: Run example
      run: cargo run --example select
    - name: Check features
      run: cargo hack check --all --ignore-private --each-feature --no-dev-deps
